---- Base app schema
-- User
CREATE TABLE "users" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,

  username varchar(128) NOT NULL,
  email varchar(128) UNIQUE,
  phone varchar(32) UNIQUE,
  occupation varchar(255),

  -- Auth
  pwd varchar(256),
  pwd_salt uuid NOT NULL DEFAULT gen_random_uuid(),
  token_salt uuid NOT NULL DEFAULT gen_random_uuid()
);



CREATE TABLE "post" {
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  user_id BIGINT NOT NULL,
  video_url varchar(255),
  text varchar(255),
  created_at varchar(32)
}

CREATE TABLE "like" {
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  user_id BIGINT NOT NULL,
  post_id BIGINT NOT NuLL,
}

CREATE TABLE "comment" {
  id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
  user_id BIGINT NOT NULL,
  post_id BIGINT NOT NuLL,

  text varchar(255),
  created_at varchar(32)
}