


const videoListResponse1 = {
    success: true,
    data: {
        1: {
            id: "10001",
            name: "A world of wonders generated by AI",
            description: "",
            url: "/video/186547-878455775.mp4"
        },
        2: {
            id: "10002",
            name: "a cute little kitten",
            description: "",
            url: "/video/191286-889670593_small.mp4"
        }
    }
}

const videoListResponse2 = {
    success: true,
    data: {
        1: {
            id: "10003",
            name: "",
            description: "",
            url: "/video/24715-345209726_small.mp4"
        },
        2: {
            id: "10004",
            name: "",
            description: "",
            url: "/video/145864-787701151.mp4"
        },
    }
}


const videoListError = {
    success: false,
    message: "oops, something went wrong!"
}
